name: firebase_dart_flutter
description: A port of the Firebase database, auth and storage client to pure Dart code for use on flutter
version: 1.1.10
homepage: https://github.com/appsup-dart/firebase_dart

environment:
  sdk: '>=2.19.0 <3.0.0'
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_dart: ^1.2.2
  platform_info: ^5.0.0
  path_provider: ^2.1.4
  hive: ^2.2.3
  package_info: ^2.0.2
  google_sign_in: ^6.2.1
  flutter_facebook_auth: ^7.1.1
  sign_in_with_apple: ^6.1.3
  url_launcher: ^6.3.1
  logging: ^1.3.0
  uni_links_desktop: ^0.1.7
  uni_links: ^0.5.1
  flutter_apns_only: ^1.6.0
  crypto: ^3.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0


flutter:
  plugin:
    platforms:
      android:
        package: be.appsup.firebase_dart_flutter
        pluginClass: FirebaseDartFlutterPlugin
